apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels: 
    app: myapp
spec:
  containers:
    - name: nginx-container
      image: nginx:1.21.1
      livenessProbe:
        httpGet:
          path: /
          port: 80
      resources:
        request:
          cpu: 250m
          memory: 250mi
        limits:
          cpu: 500m
          memory: 512mi
      ports:
        containerPort: 80
        protocol: TCP
        