---
apiVersion: v1
kind: Pod
metadata:
  name: myjenkins
spec: 
  container:
    - name: myjenkins-container
      image: jenkins/jenkins:jdk11
      livenessProbe:
        httpGet:
        path: /
        port: 8080 
      ports: 
      containerport: 8080
      name: http
      protocol: TCP


