apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
  labels:
    app: myapp
spec:
  containers:
    - name: alpine-container
      image: alpine 
      args: [sleep]
      command: [1d]
        
    
     