apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
  labels:
    app: myapp
spec:
  containers:
    - name: alpine-container
      image: alpine 
      livenessProbe: 
        httpget:
          path: /
          port: 80
      Ports:
        - containerport: 80
          protocol: TCP
          name: http 
      resources:
        requests:
          cpu: 200m
          memory: 256Mib
        limits:
          cpu: 500m
          memory: 512Mib